apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sis-configmap.yaml
  - sis-secret.yaml
  - sis-deployment.yaml
  - sis-service.yaml
  - sis-hpa.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: sis-postgres-init
    files:
      - postgres-init.sql
